### Get all

GET http://localhost:3000/players


### Get single

GET http://localhost:3000/players/7

### Create new

POST http://localhost:3000/players
Content-Type: application/json; charset=utf-8

{
    "name": "Malin Rosén",
    "jersey": 13,
    "position": "Goalie",
    "team": "Bajen"
}


### Uppdatera
PUT http://localhost:3000/players/1
Content-Type: application/json; charset=utf-8

{
    "name": "Malin3 Rosén",
    "jersey": 13,
    "position": "Goalie",
    "team": "hjehejh"
}

###Radera

DELETE http://localhost:3000/players/6
